Incomplete Project

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
data = pd.read_excel('dataset/2010 Federal STEM Education Inventory Data Set.xls')

In [5]:
data.head()

,PROGRAM,Unnamed: 1,Unnamed: 2,Unnamed: 3,FUNDING,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 245,Unnamed: 246,Unnamed: 247,Unnamed: 248,Unnamed: 249,Unnamed: 250,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254
Index Number,Investment Name,Agency,Subagency,A) Brief Description,B) Year Established,C1) Funding FY2008,C2) Funding FY2009,C3) Funding FY2010,D) Mission-specific or General STEM?,E) Agency or Mission-Related Workforce Needs?,...,NaN,NaN,Y3) Process or Implementation Evaluation Type,NaN,NaN,Y4) Portfolio Evaluation/Review Type,NaN,NaN,Y5) Expert Review Type,NaN
PRG_0001,Centers for Ocean Sciences Education Excellence ~,National Science Foundation,Directorate for Geosciences (GEO),The Division of Ocean Sciences seeks to establ...,2002,5.24,7.19,5.7,General STEM,NaN,...,NaN,NaN,NaN,NaN,NO,INDEPENDENT,NaN,NaN,INDEPENDENT,NaN
PRG_0002,Broadening Participation in Computing (BPC),National Science Foundation,Directorate for Computer & Information Science...,The BPC Program was not primarily aimed at edu...,2006,14,14,14,General STEM,NaN,...,NaN,NaN,NaN,NaN,NO,NaN,NaN,NO,NaN,NaN
PRG_0003,CISE Pathways to Revitalized Undergraduate Com...,National Science Foundation,Directorate for Computer & Information Science...,Through the CISE Pathways to Revitalized Under...,2007,5,5,4.37,General STEM,NaN,...,NaN,NaN,NaN,NaN,NO,NaN,NaN,NO,NaN,NaN
PRG_0004,Opportunities for Enhancing Diversity in the G...,National Science Foundation,Directorate for Geosciences (GEO),The Opportunities for Enhancing Diversity in t...,2002,4.57,11.79,4.18,General STEM,NaN,...,NaN,NO,INDEPENDENT,NaN,NaN,INDEPENDENT,NaN,NaN,INDEPENDENT,NaN

In [6]:
data.describe()

,Unnamed: 162,Unnamed: 165,Unnamed: 168,Unnamed: 171,Unnamed: 177,Unnamed: 180,Unnamed: 183
count,12.000000,4.000000,1.0000,1.000,2.000000,1.00,1.000
mean,1.650048,1.048625,0.0445,0.089,0.887000,1.82,2.204
std,1.910847,1.392363,NaN,NaN,1.112986,NaN,NaN
min,0.050000,0.044500,0.0445,0.089,0.100000,1.82,2.204
25%,0.198375,0.048625,0.0445,0.089,0.493500,1.82,2.204
50%,0.737625,0.575000,0.0445,0.089,0.887000,1.82,2.204
75%,3.250457,1.575000,0.0445,0.089,1.280500,1.82,2.204
max,5.000000,3.000000,0.0445,0.089,1.674000,1.82,2.204

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 254 entries, Index Number to nan
Columns: 255 entries, PROGRAM to Unnamed: 254
dtypes: float64(7), object(248)
memory usage: 508.0+ KB